import React, { useEffect, useMemo, useState } from 'react';
import { ExtractedVehicleSchedule } from '../types/scenario';
import { validateSchedule } from '../services/scenarioValidationService';
import { ScenarioValidationPanel } from './ScenarioValidationPanel';

export const ExtractionReview: React.FC<{ rows: ExtractedVehicleSchedule[]; onApprove: (rows: ExtractedVehicleSchedule[]) => void }> = ({ rows, onApprove }) => {
  const [items, setItems] = useState(rows); const result = useMemo(() => validateSchedule(items), [items]);
  useEffect(() => setItems(rows), [rows]);
  const change = (index: number, key: keyof ExtractedVehicleSchedule, value: string) => setItems((previous) => previous.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: ['currentSOC','targetSOC','batteryCapacityKwh','requiredEnergyKwh','maxPowerKw'].includes(key) ? (value === '' ? null : Number(value)) : (value || null) } : row));
  return <div className="space-y-4"><ScenarioValidationPanel total={items.length} result={result}/><div className="bg-white border border-[#c4c6d0]/50 rounded-xl overflow-auto shadow-xs"><table className="w-full text-[11px] min-w-[1100px]"><thead className="bg-[#eff4ff] text-[#00163d]"><tr>{['Status','Vehicle ID','Model','Route','Priority','Arrival','Departure','Current SOC','Target SOC','Battery','Energy','Max Power','Source',''].map((h) => <th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{items.map((row, index) => { const bad = result.invalidRows.includes(row); return <tr key={`${row.sourcePage}-${row.sourceRow}`} className="border-t border-slate-100"><td className={`p-2 font-bold ${bad ? 'text-[#ba1a1a]' : row.confidence === 'WARNING' ? 'text-amber-700' : 'text-[#006c4a]'}`}>{bad ? 'ERROR' : row.confidence}</td>{(['vehicleId','model','route','priority','arrivalTime','departureTime','currentSOC','targetSOC','batteryCapacityKwh','requiredEnergyKwh','maxPowerKw'] as const).map((key) => <td key={key} className="p-1"><input value={row[key] ?? ''} onChange={(e) => change(index, key, e.target.value)} className="w-full min-w-16 p-1 border border-slate-200 rounded"/></td>)}<td className="p-2">p{row.sourcePage}, r{row.sourceRow}</td><td className="p-2"><button onClick={() => setItems((previous) => previous.filter((_, i) => i !== index))} className="text-[#ba1a1a]">Remove</button></td></tr>; })}</tbody></table></div><div className="flex justify-end"><button disabled={!!result.errors.length || !items.length} onClick={() => onApprove(items)} className="px-4 py-2 bg-[#00163d] text-white text-[12px] font-semibold rounded-md disabled:opacity-50">Approve Schedule</button></div></div>;
};
