import React, { useRef, useState } from 'react';
import { extractVehicleSchedule } from '../services/pdfExtractionService';
import { ExtractionResult, ExtractionStatus } from '../types/scenario';

export const PdfScheduleImport: React.FC<{ onExtracted: (result: ExtractionResult) => void }> = ({ onExtracted }) => {
  const [file, setFile] = useState<File | null>(null); const [status, setStatus] = useState<ExtractionStatus>('IDLE'); const [error, setError] = useState<string | null>(null); const input = useRef<HTMLInputElement>(null);
  const choose = (candidate?: File) => { if (!candidate) return; if (!candidate.name.toLowerCase().endsWith('.pdf')) { setError('Please select a PDF file.'); setStatus('ERROR'); return; } setFile(candidate); setError(null); setStatus('FILE_SELECTED'); };
  const extract = async () => { if (!file) return; setStatus('EXTRACTING'); setError(null); try { const result = await extractVehicleSchedule(file); setStatus(result.extractionStatus); if (result.extractionStatus === 'ERROR') setError(result.extractionWarnings[0] || 'No vehicle schedule rows were detected in this PDF.'); onExtracted(result); } catch (reason: any) { setError(reason?.message || 'Unable to extract this PDF.'); setStatus('ERROR'); } };
  return <div className="bg-white border border-[#c4c6d0]/50 rounded-xl p-5 shadow-xs"><input ref={input} type="file" accept="application/pdf" className="hidden" onChange={(e) => choose(e.target.files?.[0])}/><div onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); choose(e.dataTransfer.files?.[0]); }} className="border-2 border-dashed border-[#c4c6d0] rounded-lg p-8 text-center bg-[#eff4ff]"><span className="material-symbols-outlined text-[32px] text-[#00163d]">upload_file</span><p className="font-semibold text-[#00163d] mt-2">Drop a vehicle schedule PDF here</p><p className="text-[12px] text-[#747780] mt-1">The file is processed locally in your browser.</p><button onClick={() => input.current?.click()} className="mt-3 px-3 py-2 text-[12px] font-semibold border border-[#c4c6d0] bg-white rounded-md">Browse / Select PDF</button></div>{file && <div className="mt-3 flex items-center justify-between text-[12px] text-[#00163d]"><span>{file.name} · {(file.size / 1024).toFixed(1)} KB</span><button onClick={() => { setFile(null); setStatus('IDLE'); }} className="text-[#ba1a1a]">Remove file</button></div>}{error && <p className="mt-3 text-[12px] text-[#ba1a1a]">{error}</p>}<div className="mt-4 flex justify-between items-center"><span className="text-[11px] text-[#747780]">Status: <strong>{status}</strong></span><button disabled={!file || status === 'EXTRACTING'} onClick={extract} className="px-4 py-2 bg-[#00163d] text-white rounded-md text-[12px] font-semibold disabled:opacity-50">{status === 'EXTRACTING' ? 'Extracting…' : 'Extract Schedule'}</button></div></div>;
};
